- name: Add R Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

- name: Add R apt repository
  apt_repository:
    repo: deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu {{ ansible_lsb.codename }}/
    state: present

- name: Install R
  apt: 
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - r-base
    - r-base-dev

- name: Create R directories
  file:
    path: '{{ r_dir }}'
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Get R installation directory
  command: R RHOME
  changed_when: false
  register: get_install_dir

- name: Set r_install_dir
  set_fact:
    r_install_dir: '{{ get_install_dir.stdout }}'

- name: Create R link
  file:
    src: '{{ r_install_dir }}'
    dest: '{{ r_home }}'
    state: link
    group: vagrant
    owner: vagrant

- name: Install R packages
  cran_pkg:
    name: '{{ item }}'
    lib: '{{ r_home }}/site-library'
    repo: '{{ r_cran }}'
  with_items: '{{ r_pkgs }}'

- name: Create Renviron.site
  template:
    src: Renviron.site.j2
    dest: '{{ r_home }}/etc/Renviron.site'

- name: Create Rprofile.site
  template:
    src: Rprofile.site.j2
    dest: '{{ r_home }}/etc/Rprofile.site'

- name: Add R environment configuration file
  template:
    src: env-r.sh.j2
    dest: /etc/profile.d/env-r.sh
