---
- name: Check if hadoop is installed
  stat:
    path: '{{ hadoop_install_dir }}/bin/hadoop'
  register: hadoop_installed
  changed_when: false

- block:

    - name: Download Hadoop binary
      get_url:
        url: '{{ hadoop_download_url }}'
        dest: '/tmp/{{ hadoop_path }}.tar.gz'

    - name: Create Hadoop directory
      file:
        path: '{{ hadoop_dir }}'
        state: directory
        owner: '{{ dst_user }}'
        group: '{{ dst_group }}'
        mode: 0755


    - name: Unarchive Hadoop
      unarchive:
        src: '/tmp/{{ hadoop_path }}.tar.gz'
        dest: '{{ hadoop_dir }}'
        creates: '{{ hadoop_install_dir }}'
        copy: no
        owner: '{{ dst_user }}'
        group: '{{ dst_group }}'
        mode: 0755

  when: not hadoop_installed.stat.exists

- name: Remove Hadoop binary
  file:
    path: '/tmp/{{ hadoop_path }}.tar.gz'
    state: absent


- name: Create current link
  file:
    src: '{{ hadoop_install_dir }}'
    dest: '{{ hadoop_home }}'
    state: link
    owner: '{{ dst_user }}'
    group: '{{ dst_group }}'

- name: Add Hadoop environment configuration file
  template:
    src: env-hadoop.sh.j2
    dest: /etc/profile.d/env-hadoop.sh
