- name: Check if RStudio is installed
  command: dpkg-query -W rstudio-server
  register: rstudio_installed
  changed_when: false
  failed_when: false

- name: Download and Install RStudio Server
  apt:
    deb: '{{ rstudio_pkg_url }}'
    state: present
  when: rstudio_installed.rc == 1

- name: Create RStudio directories
  file:
    path: '{{ rstudio_home }}'
    state: directory
    owner: '{{ dst_user }}'
    group: '{{ dst_group }}'
    mode: 0755

- name: Link RStudio sbin directory
  file:
    src: '{{ rstudio_bin_dir }}'
    dest: '{{ rstudio_home }}/sbin'
    state: link
    owner: '{{ dst_user }}'
    group: '{{ dst_group }}'

- name: Link RStudio conf directory
  file:
    src: '{{ rstudio_conf_dir }}'
    dest: '{{ rstudio_home }}/conf'
    state: link
    owner: '{{ dst_user }}'
    group: '{{ dst_group }}'

- name: Link RStudio lib directory
  file:
    src: '{{ rstudio_lib_dir }}'
    dest: '{{ rstudio_home }}/lib'
    state: link
    owner: '{{ dst_user }}'
    group: '{{ dst_group }}'

- name: Link RStudio log directory
  file:
    src: '{{ rstudio_log_dir }}'
    dest: '{{ rstudio_home }}/log'
    state: link
    owner: '{{ dst_user }}'
    group: '{{ dst_group }}'

- name: Create RStudio configuration
  template:
    src: rserver.conf.j2
    dest: '{{ rstudio_conf_dir }}/rserver.conf'
  notify: 
    - restart rstudio
