- name: Define java_package
  set_fact:
    java_package: "{{ vars['java'][java.type]['package'] }}"

- name: Define java_path
  set_fact:
    java_path: "{{ vars['java'][java.type]['path'] }}"

- block:

    - name: Add WebUpd8 Apt repo
      apt_repository:
        repo: '{{ java.oracle.repo }}'
        state: present
        update_cache: yes

    - name: Accept Oracle Java License
      debconf:
        name: '{{ java.oracle.package }}'
        question: 'shared/accepted-oracle-license-v1-1'
        vtype: 'select'
        value: 'true'

  when: java.type == 'oracle'

- name: Install Java
  apt:
    name: '{{ java_package }}'
    state: installed

- name: Create app directory link
  file:
    src: '{{ java_path }}'
    dest: '{{ java_dir }}'
    state: link
    owner: vagrant
    group: vagrant

- name: Add Java environment configuration file
  template:
    src: env-java.sh.j2
    dest: /etc/profile.d/env-java.sh
