- name: Add WebUpd8 Apt repo
  apt_repository:
    repo: 'ppa:webupd8team/java'
    state: present
    update_cache: yes

- name: Accept Oracle Java License
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    vtype: 'select'
    value: 'true'

- name: Install 
  apt:
    name: 'oracle-java8-installer'
    state: installed
