- name: Define java_package
  set_fact:
    java_package: "{{ java[java_type].package }}"

- name: Define java_path
  set_fact:
    java_path: "{{ java[java_type].path }}"

- block:

    - name: Add WebUpd8 Apt repo
      apt_repository:
        repo: '{{ java.oracle.repo }}'
        state: present
        update_cache: yes

    - name: Accept Oracle Java License
      debconf:
        name: '{{ java.oracle.package }}'
        question: 'shared/accepted-oracle-license-v1-1'
        vtype: 'select'
        value: 'true'

  when: java.type == 'oracle'

- name: Install Java
  apt:
    name: '{{ java_package }}'
    state: installed

- name: Create Java directory
  file:
    path: '{{ java_dir }}'
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Create current link
  file:
    src: '{{ java_path }}'
    dest: '{{ java_dir }}/current'
    state: link

- name: Add Java environment configuration file
  template:
    src: env-java.sh.j2
    dest: /etc/profile.d/env-java.sh

- name: Move Oracle Java environment files
  command: mv {{ item }} {{ item }}.bak
  args:
    chdir: /etc/profile.d
    creates: '/etc/profile.d/{{ item }}.bak'
    removes: '/etc/profile.d/{{ item }}'
  with_items:
    - jdk.sh
    - jdk.csh
  when: java.type == 'oracle'
