- name: Check if Conda is already installed
  stat:
    path: '{{ conda_install_dir }}/bin/conda'
  register: conda_installed
  changed_when: false

- block:

    - name: Download Conda install script
      get_url:
        url: '{{ conda_url }}'
        dest: '/tmp/{{ conda_script }}'
        mode: 0755

    - name: Create Conda directory
      file:
        path: '{{ conda_dir }}'
        state: directory
        owner: '{{ dst_user }}'
        group: '{{ dst_group }}'
        mode: 0755

    - name: Install Conda
      command: /tmp/{{ conda_script }} -b -p {{ conda_install_dir }}
      args:
        creates: '{{ conda_install_dir }}'

  when: not conda_installed.stat.exists 

- name: Remove Conda install script
  file:
    path: '/tmp/{{ conda_script }}'
    state: absent

- name: Install packages into root environment
  conda_pkg:
    name: ipython
    path: '{{ conda_install_dir }}'

- name: Create Conda environment
  conda_env:
    name: '{{ conda_env }}'
    path: '{{ conda_install_dir }}'

- name: Install packages in Conda environment
  conda_pkg:
    name: '{{ item }}'
    env: '{{ conda_env }}'
    path: '{{ conda_install_dir }}'
  with_items: '{{ conda_pkgs }}'

- name: Install pip packages in Conda environment
  pip: 
    name: '{{ item }}'
    executable: '{{ conda_env_dir}}/bin/pip'
  with_items: '{{ conda_pip_pkgs }}'
  when: not conda_pip_pkgs is none

- name: Update Conda install directory owner
  file:
    path: '{{ conda_install_dir }}'
    state: directory
    owner: '{{ dst_user }}'
    group: '{{ dst_group }}'
    recurse: yes
    mode: 0755

- name: Create current link
  file:
    src: '{{ conda_install_dir }}'
    dest: '{{ conda_home }}'
    state: link
    owner: '{{ dst_user }}'
    group: '{{ dst_group }}'
    
- name: Add Conda environment configuration file
  template:
    src: env-conda.sh.j2
    dest: /etc/profile.d/env-conda.sh
